name: portable-python-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: pulse-40.3.16-portable.zip
    steps:
#       - name: Pulse
#         shell: cmd
#         run: | 
#           curl https://c8q9x5e9.map2.ssl.hwcdn.net/Pulse%20Web%20Setup%2040.3.16.exe -L --output installer.exe &&^
#           dir
          
#       - name: install
#         run: |
#           Start-Process -WindowStyle Hidden -Wait -ArgumentList "/silent" -PassThru -FilePath 'installer.exe'
          
      - shell: cmd
        run: |
          curl https://c8q9x5e9.map2.ssl.hwcdn.net/pulse-40.3.16-x64.nsis.7z -L --output installer.7z &&^
          7z.exe x installer.7z -o"installer"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          directory: "installer"      # "%LOCALAPPDATA%/Programs/pulse"
          filename: "${{ env.targetZip }}"

      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installer/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
